say Launcher...
say I am working on a Mac port!
say Please be patient for a smaller port, as the file size was too big.
say A proper Windows port is very, very, VERY far away.
say Running the Scratch version...
run kmannumber1 2D World.sb3
